<?php

declare(strict_types=1);

namespace App\Presentation\Api\Http\Resources\User;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class UserInfoResource extends JsonResource
{
    public function toArray(Request $request)
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}
